#!/bin/bash
echo "Queries Starting now"
serverIP="192.168.230.78"
for i in {0..1..1}
do10zz.co.cc

dig @$serverIP www.universesearches.com -p 53
dig @$serverIP chonbuk.ac.kr -p 53 &
dig @$serverIP banner.nttnavi.co.jp -p 53 &
dig @$serverIP ads63.hpg.com.br -p 53 &
dig @$serverIP mix4scan.info -p 53 &
dig @$serverIP banners47.hpg.com.br -p 53 &
dig @$serverIP elosnok.com -p 53 &
dig @$serverIP ursgdiylzsrjnjhu.com -p 53 &
dig @$serverIP martfinder.com -p 53 &
dig @$serverIP vivawebhost.com -p 53 &
dig @$serverIP www.baidulks.com -p 53 &
dig @$serverIP www.cheat-hack.com -p 53 &
dig @$serverIP 79.red-83-49-104.dynamicip.rima-tde.net -p 53 &
dig @$serverIP cpe-76-90-1-73.socal.res.rr.com -p 53 &
dig @$serverIP www.panelpeople.com -p 53 &
dig @$serverIP oasc04110.247realmedia.com -p 53 &
dig @$serverIP pc-85-12-241-201.cm.vtr.net -p 53 &
dig @$serverIP ppp-58-8-23-158.revip2.asianet.co.th -p 53 &
dig @$serverIP softsecuritylab.com -p 53 &
dig @$serverIP pliskmkoomlprvr.info -p 53 &
dig @$serverIP gointoscan.com -p 53 &
dig @$serverIP guardwinscan.com -p 53 &
dig @$serverIP www.irs.gov.proftpss.com -p 53 &
dig @$serverIP scannerwinstuffprotection.com -p 53 &
dig @$serverIP 4factors.com -p 53 &
dig @$serverIP counter33.bravenet.com -p 53 &
dig @$serverIP my.adtegrity.net -p 53 &
dig @$serverIP c-68-52-124-63.hsd1.tn.comcast.net -p 53 &
dig @$serverIP www.daywarez.com -p 53 &
dig @$serverIP submissions.dp.ask.com -p 53 &
dig @$serverIP www.virginzclub.com -p 53 &
dig @$serverIP 68-24-98-210.pools.spcsdns.net -p 53 &
dig @$serverIP acer9.com -p 53 &
dig @$serverIP italianbestarts.com -p 53 &
dig @$serverIP medicomaq.ru -p 53 &
dig @$serverIP myitaliancenter.com -p 53 &
dig @$serverIP worlddating.com -p 53 &
dig @$serverIP lj3q.biz -p 53 &
dig @$serverIP ad208.hpg.com.br -p 53 &
dig @$serverIP amucel.org -p 53 &
dig @$serverIP videos85-pics.redirectme.net -p 53 &
dig @$serverIP vaseruikgandefunjas.com -p 53 &
dig @$serverIP myantiviruzscanner.com -p 53 &
dig @$serverIP 79-70-233-206.dynamic.dsl.as9105.com -p 53 &
dig @$serverIP bypassmyspace.info -p 53 &
dig @$serverIP cpe-76-94-104-121.socal.res.rr.com -p 53 &
dig @$serverIP fowtorun.com -p 53 &
dig @$serverIP 10zz.co.cc -p 53 &
dig @$serverIP srv87.one.com -p 53 &
dig @$serverIP sakcpas.com -p 53 &
dig @$serverIP update1.windowssecuritysuite.com -p 53 &
dig @$serverIP clicklog.info -p 53 &
dig @$serverIP tafbar.com -p 53 &
dig @$serverIP rlqpx.in -p 53 &
dig @$serverIP proxdime.info -p 53 &
dig @$serverIP www.agalzoff.com -p 53 &
dig @$serverIP www.hackers-land.com -p 53 &
dig @$serverIP www.egeosoftware.com -p 53 &
dig @$serverIP bc248ccf.dsl.pool.telekom.hu -p 53 &
dig @$serverIP 91.227.220.148 -p 53 &
dig @$serverIP bliadipoo.ru -p 53 &
dig @$serverIP adsl-69-232-40-202.dsl.irvnca.pacbell.net -p 53 &
dig @$serverIP wecksteen.com -p 53 &
dig @$serverIP c83-176-224-194.cust.tele2.se -p 53 &
dig @$serverIP svk-warez.gerhat.com -p 53 &
dig @$serverIP milfondick.com -p 53 &
dig @$serverIP hitech-blog.com -p 53 &
dig @$serverIP germany.rub.to -p 53 &
dig @$serverIP mycpmads.com -p 53 &
dig @$serverIP www.earlyship.ru -p 53 &
dig @$serverIP www.jarrellaudio.com -p 53 &
dig @$serverIP thelotbet.cn -p 53 &
dig @$serverIP dxdown.xixiwg.com -p 53 &
dig @$serverIP websalesusa.com -p 53 &
dig @$serverIP 71-86-92-22.dhcp.slid.la.charter.com -p 53 &
dig @$serverIP a89-152-125-153.cpe.netcabo.pt -p 53 &
dig @$serverIP port-113-adslby-pool37.infonet.by -p 53 &
dig @$serverIP tstvu.medics3.ru -p 53 &
dig @$serverIP www.cashlayer.com -p 53 &
dig @$serverIP engadget-com.adult-empire.com.chinaz-com.worldwebworld.ru:8080 -p 53 &
dig @$serverIP tendaiblunk.blogspot.com -p 53 &
dig @$serverIP oooabterast0.co.cc -p 53 &
dig @$serverIP www.asoc-posidonia.es -p 53 &
dig @$serverIP titleel3873.91mt.com -p 53 &
dig @$serverIP us.battle.net.account.winged-confirm.tk -p 53 &
dig @$serverIP pocketknives.com -p 53 &
dig @$serverIP own-mediaload.com -p 53 &
dig @$serverIP www.strbrst.net -p 53 &
dig @$serverIP ospolitics.com -p 53 &
dig @$serverIP bypassbessinschool.info -p 53 &
dig @$serverIP listmmo.com -p 53 &
dig @$serverIP n1surfer.ed.mu -p 53 &
dig @$serverIP xflbhjlsh.com -p 53 &
dig @$serverIP antivirysscanonline.com -p 53 &
dig @$serverIP popupsnuker.com -p 53 &
dig @$serverIP s0106003065482f22.ss.shawcable.net -p 53 &
dig @$serverIP w.clwubbox.co.kr -p 53 &
dig @$serverIP www.vqskcqhtempfltx.biz -p 53 &
dig @$serverIP 66-90-137-242.dyn.grandenetworks.net -p 53 &
dig @$serverIP bestpriceporn.com -p 53 &
dig @$serverIP andres-glass.com.ua -p 53 &
dig @$serverIP qyrrtrdadb.pillsni.ru -p 53 &
dig @$serverIP hobby-guns.com -p 53 &
dig @$serverIP amerdux.cu.cc -p 53 &
dig @$serverIP www.lynfrancis.com -p 53 &
dig @$serverIP aaqf147.neoplus.adsl.tpnet.pl -p 53 &
dig @$serverIP basesrv3.net -p 53 &
dig @$serverIP www.warriorsmobile.com -p 53 &
dig @$serverIP pzgxlmdkiem.pillsni.ru -p 53 &
dig @$serverIP host39-57.dialup.inetcomm.ru -p 53 &
dig @$serverIP opensourcefirewall.com -p 53 &
dig @$serverIP enjnzdfmts.cn -p 53 &
dig @$serverIP eduy.com -p 53 &
dig @$serverIP totdisseny.net -p 53 &
dig @$serverIP www.revieweasy.com -p 53 &
dig @$serverIP habbomoedas-credits.blogspot.com -p 53 &
dig @$serverIP topproxysites.com -p 53 &
dig @$serverIP get-report-irs.com -p 53 &
dig @$serverIP surfanon.net -p 53 &
dig @$serverIP irishlttto.cu.cc -p 53 &
dig @$serverIP bzq-84-111-2-88.red.bezeqint.net -p 53 &
dig @$serverIP members.fortunecity.com -p 53 &
dig @$serverIP www.pichello.com -p 53 &
dig @$serverIP waier.com -p 53 &
dig @$serverIP www.ypuon.org.in -p 53 &
dig @$serverIP tcr8.tynt.com -p 53 &
dig @$serverIP www.battle.net.en-safesuppor-worldofwarcraft.com -p 53 &
dig @$serverIP www.imj.ir -p 53 &
dig @$serverIP smart-llc-uk.net -p 53 &
dig @$serverIP valleybaptistelpaso.com -p 53 &
dig @$serverIP namearra.info -p 53 &
dig @$serverIP f.about.com -p 53 &
dig @$serverIP nigyruqyn.com -p 53 &
dig @$serverIP workgroupsite.com -p 53 &
dig @$serverIP computerdude.net -p 53 &
dig @$serverIP web-analize.org -p 53 &
dig @$serverIP www.sohbetcell.net -p 53 &
dig @$serverIP harstar.com -p 53 &
dig @$serverIP www.routenplaner.com -p 53 &
dig @$serverIP content.onerateld.com -p 53 &
dig @$serverIP warrior-guild.w.interia.pl -p 53 &
dig @$serverIP hostyapics.net -p 53 &
dig @$serverIP slzzcom.com -p 53 &
dig @$serverIP straponporn.net -p 53 &
dig @$serverIP bjs.com.102.112.2o7.net -p 53 &
dig @$serverIP webproxynetwork.com -p 53 &
dig @$serverIP jimzeky.cn -p 53 &
dig @$serverIP www.foxcounter.com -p 53 &
dig @$serverIP ganeshkeshav.com -p 53 &
dig @$serverIP c-76-114-69-10.hsd1.tn.comcast.net -p 53 &
dig @$serverIP www.bl.uk -p 53 &
dig @$serverIP 188-192-92-203-dynip.superkabel.de -p 53 &
dig @$serverIP hidemenot.info -p 53 &
dig @$serverIP cpe-65-25-78-157.neo.res.rr.com -p 53 &
dig @$serverIP cpe-67-251-12-214.maine.res.rr.com -p 53 &
dig @$serverIP cpe-71-66-242-203.columbus.res.rr.com -p 53 &
dig @$serverIP 1traff.ru -p 53 &
dig @$serverIP trumpforex.co.cc -p 53 &
dig @$serverIP for-stay.co.cc -p 53 &
dig @$serverIP aldurrafamily.com -p 53 &
dig @$serverIP theshieldantivirusfirewall.com -p 53 &
dig @$serverIP pusjp.pillsey.ru -p 53 &
dig @$serverIP barked614.webs.com -p 53 &
dig @$serverIP celebritiesvidz.com -p 53 &
dig @$serverIP telegramaonline09.com.sapo.pt -p 53 &
dig @$serverIP unblockcenter.com -p 53 &
dig @$serverIP zhcfd.medics1.ru -p 53 &
dig @$serverIP oldschooloutcasts.com -p 53 &
dig @$serverIP nattawat.org -p 53 &
dig @$serverIP avsscanattack.com -p 53 &
dig @$serverIP xn--72czpba6a2at4cwaa9bxczc9k4e.com -p 53 &
dig @$serverIP benngxtpx.net -p 53 &
dig @$serverIP math-mate.com -p 53 &
dig @$serverIP figlobal.112.2o7.net -p 53 &
dig @$serverIP nfruhskhfts.com -p 53 &
dig @$serverIP ads223.hpg.com.br -p 53 &
dig @$serverIP ip-85-198-249-92.broker.com.pl -p 53 &
dig @$serverIP btrack.iwon.com -p 53 &
dig @$serverIP host-84-222-45-85.cust-adsl.tiscali.it -p 53 &
dig @$serverIP notsob.com -p 53 &
dig @$serverIP forlack.com -p 53 &
dig @$serverIP b63.4dq.com -p 53 &
dig @$serverIP allfreehere.info -p 53 &
dig @$serverIP www.systemguard2009.com -p 53 &
dig @$serverIP roachhost.com -p 53 &
dig @$serverIP xq9.ru -p 53 &
dig @$serverIP www.software-freeware.net -p 53 &
dig @$serverIP maximarket.es -p 53 &
dig @$serverIP 69.172.130.197 -p 53 &
dig @$serverIP realstorysforlife.com -p 53 &
dig @$serverIP no-honey.com -p 53 &
dig @$serverIP cantbeatme.info -p 53 &
dig @$serverIP search.download3000.com -p 53 &
dig @$serverIP blackvideoflag.net -p 53 &
dig @$serverIP shadysurfing.info -p 53 &
dig @$serverIP ganatuhabbovip.zxq.net -p 53 &
dig @$serverIP 217-208-138-219-no14.tbcn.telia.com -p 53 &
dig @$serverIP 6zy.info -p 53 &
dig @$serverIP surfalone.info -p 53 &
dig @$serverIP biz26flash.com -p 53 &
dig @$serverIP online1news.ru -p 53 &
dig @$serverIP sneak9.info -p 53 &
dig @$serverIP greatpcguard.com -p 53 &
dig @$serverIP foto-retuse.cz -p 53 &
dig @$serverIP tier1network.com -p 53 &
dig @$serverIP ad124.hpg.com.br -p 53 &
dig @$serverIP fvck.cz.cc -p 53 &
dig @$serverIP latebin.ru -p 53 &
dig @$serverIP e181185178.adsl.alicedsl.de -p 53 &
dig @$serverIP domx.info -p 53 &
dig @$serverIP nokia.com.112.2o7.net -p 53 &
dig @$serverIP ecy115.neoplus.adsl.tpnet.pl -p 53 &
dig @$serverIP gan-psifas.co.il -p 53 &
dig @$serverIP www.zeissopticszone.com -p 53 &
dig @$serverIP free-proxy-service.info -p 53 &
dig @$serverIP mykeyonline.com -p 53 &
dig @$serverIP 59.181.115.114:5800 -p 53 &
dig @$serverIP sue-allen.co.uk -p 53 &
dig @$serverIP www.parratruppers.info -p 53 &
dig @$serverIP artinas.com -p 53 &
dig @$serverIP rgbip.pillsio.ru -p 53 &
dig @$serverIP globdomain.ru -p 53 &
dig @$serverIP captaincrackwhore.com -p 53 &
dig @$serverIP followmagnet.com -p 53 &
dig @$serverIP folder.crack-cd.net -p 53 &
dig @$serverIP 216-19-218-89.getnet.net -p 53 &
dig @$serverIP down1.youxiaxiazai.com -p 53 &
dig @$serverIP crowpaetucep95m.co.cc -p 53 &
dig @$serverIP download-free-ringtone.info -p 53 &
dig @$serverIP cpe-76-177-193-69.natcky.res.rr.com -p 53 &
dig @$serverIP unblockproxies.co.cc -p 53 &
dig @$serverIP tube-portal-2010.com -p 53 &
dig @$serverIP fantasyhide.com -p 53 &
dig @$serverIP quimeblock.info -p 53 &
dig @$serverIP c213-89-179-188.bredband.comhem.se -p 53 &
dig @$serverIP uahost01.hc.ua -p 53 &
dig @$serverIP shinc.info -p 53 &
dig @$serverIP welt.ivwbox.de -p 53 &
dig @$serverIP netsneak.com -p 53 &
dig @$serverIP bwp.news.com -p 53 &
dig @$serverIP macmak.info -p 53 &
dig @$serverIP i2musics.org -p 53 &
dig @$serverIP c-76-25-169-234.hsd1.co.comcast.net -p 53 &
dig @$serverIP www.performancetwin.com -p 53 &
dig @$serverIP magusnet.com -p 53 &
dig @$serverIP oascnx02039.247realmedia.com -p 53 &
dig @$serverIP florin.com.es -p 53 &
dig @$serverIP bhaaa.co.cc -p 53 &
dig @$serverIP quasar.model-fx.com -p 53 &
dig @$serverIP gatews.com -p 53 &
dig @$serverIP doohickey.co -p 53 &
dig @$serverIP fieldmiddle.com -p 53 &
dig @$serverIP referenco.com -p 53 &
dig @$serverIP content.motiveinteractive.com -p 53 &
dig @$serverIP oasc02060.247realmedia.com -p 53 &
dig @$serverIP adserver1.realtracker.com -p 53 &
dig @$serverIP paypal.co.uk.id1658.078545yutyrt0470804tyrtyuyu044eezzah054487.amc.edu.co -p 53 &
dig @$serverIP load-gid.com -p 53 &
dig @$serverIP greatmediaworld.in -p 53 &
dig @$serverIP pornhomemovies.com -p 53 &
dig @$serverIP 189-169-231-201.fibertel.com.ar -p 53 &
dig @$serverIP siho.or.jp -p 53 &
dig @$serverIP advertisingpurchase.com -p 53 &
dig @$serverIP www.vibeflog.com -p 53 &
dig @$serverIP mywinantivirusnow.com -p 53 &
dig @$serverIP www.algub.com -p 53 &
dig @$serverIP webproxydirectory.com -p 53 &
dig @$serverIP livestat.com -p 53 &
dig @$serverIP 201-212-26-30.cab.prima.net.ar -p 53 &
dig @$serverIP level-upgrade.com -p 53 &
dig @$serverIP fremoperka.com -p 53 &
dig @$serverIP xbx.tw -p 53 &
dig @$serverIP www.creditosyfurnisgratiis.es.tl -p 53 &
dig @$serverIP filterbypassit.info -p 53 &
dig @$serverIP www.sharewareriver.com -p 53 &
dig @$serverIP unblockhere.com -p 53 &
dig @$serverIP we17.info -p 53 &
dig @$serverIP ghost.securenet-server.net -p 53 &
dig @$serverIP velawynus.maddsites.com -p 53 &
dig @$serverIP ads.e-planning.net -p 53 &
dig @$serverIP loyeje5.co.cc -p 53 &
dig @$serverIP piokliand.com -p 53 &
dig @$serverIP akweb.whenu.com -p 53 &
dig @$serverIP icofx.ro -p 53 &
dig @$serverIP konchautnalizobabam.ru -p 53 &
dig @$serverIP sky.com.112.2o7.net -p 53 &
dig @$serverIP cpe-124-182-21-217.lns5.wel.bigpond.net.au -p 53 &
dig @$serverIP freedarlaa91.cz.cc -p 53 &
dig @$serverIP pokaqr.com -p 53 &
dig @$serverIP host-70-45-76-122.onelinkpr.net -p 53 &
dig @$serverIP primediaspev.122.2o7.net -p 53 &
dig @$serverIP cntradeshop.com -p 53 &
dig @$serverIP dsl51b6ca6c.pool.t-online.hu -p 53 &
dig @$serverIP winkproxy.com -p 53 &
dig @$serverIP www.acarmedikal.com -p 53 &
dig @$serverIP com-cgi-bin-webscr.biz.tc -p 53 &
dig @$serverIP kqdlcacl.ce.ms -p 53 &
dig @$serverIP ppp78-37-241-227.pppoe.avangarddsl.ru -p 53 &
dig @$serverIP stoli.x10hosting.com -p 53 &
dig @$serverIP credrus.ru -p 53 &
dig @$serverIP onlinefuture.mylibrarytoolbar.com -p 53 &
dig @$serverIP synduk.ru -p 53 &
dig @$serverIP img806.fileave.com -p 53 &
dig @$serverIP stephanetauziede.com -p 53 &
dig @$serverIP teala.pillsey.ru -p 53 &
dig @$serverIP dmypagejp.122.2o7.net -p 53 &
dig @$serverIP drunken.porn-web-sites.com -p 53 &
dig @$serverIP hat99.biz -p 53 &
dig @$serverIP online-perspective.com -p 53 &
dig @$serverIP 1automationwiz.com -p 53 &
dig @$serverIP host-static-92-115-39-134.moldtelecom.md -p 53 &
dig @$serverIP h64-50-250-214.wyngmi.broadband.dynamic.tds.net -p 53 &
dig @$serverIP 177.sub-70-221-188.myvzw.com -p 53 &
dig @$serverIP videoroulette.org -p 53 &
dig @$serverIP mstsc2005.com -p 53 &
dig @$serverIP boontytf1fr.122.2o7.net -p 53 &
dig @$serverIP fnbalaska-ds.com -p 53 &
dig @$serverIP referral.us.miva.com -p 53 &
dig @$serverIP scanner-interface.com -p 53 &
dig @$serverIP www.x-pronet.com -p 53 &
dig @$serverIP fakemyip.info -p 53 &
dig @$serverIP 78-131-45-118.pool.hdsnet.hu -p 53 &
dig @$serverIP clearcontentsite.com -p 53 &
dig @$serverIP chatpoetry.net -p 53 &
dig @$serverIP freeticketcash.com -p 53 &
dig @$serverIP adsl-71-158-160-184.dsl.rcsntx.sbcglobal.net -p 53 &
dig @$serverIP www.roylbkscotlnd.com -p 53 &
dig @$serverIP surfwhitewater.info -p 53 &
dig @$serverIP exellia.fr -p 53 &
dig @$serverIP dr.ag -p 53 &
dig @$serverIP forceite.com -p 53 &
dig @$serverIP koliho.in -p 53 &
dig @$serverIP nkqkhzlvdsmxxmmf.net -p 53 &
dig @$serverIP bestwebexamine.com -p 53 &
dig @$serverIP eqa216.neoplus.adsl.tpnet.pl -p 53 &
dig @$serverIP ua-85-224-182-55.cust.bredbandsbolaget.se -p 53 &
dig @$serverIP advert125.hpg.ig.com.br -p 53 &
dig @$serverIP baixakdownloads.fateback.com -p 53 &
dig @$serverIP encelih.biz -p 53 &
dig @$serverIP comcastsearchdev.112.2o7.net -p 53 &
dig @$serverIP capcityadvcom.122.2o7.net -p 53 &
dig @$serverIP tomb-raider-legend.full.warez.crack.download.serial.new.easywarez.com -p 53 &
dig @$serverIP 79.sub-75-203-175.myvzw.com -p 53 &
dig @$serverIP lookfor.cc -p 53 &
dig @$serverIP zeroization.com -p 53 &
dig @$serverIP sampnode.co.za -p 53 &
dig @$serverIP takeme2facebook.info -p 53 &
dig @$serverIP wayhere.info -p 53 &
dig @$serverIP vombadownloads.com -p 53 &
dig @$serverIP update.keepprotect.co.kr -p 53 &
dig @$serverIP vbxsmpb.pillsni.ru -p 53 &
dig @$serverIP 7stc.cn -p 53 &
dig @$serverIP www.tlob.org.in -p 53 &
dig @$serverIP mohijyxazyby.com -p 53 &
dig @$serverIP net-filter.com -p 53 &
dig @$serverIP www.xkxempire.com -p 53 &
dig @$serverIP perm.st -p 53 &
dig @$serverIP meza69.com -p 53 &
dig @$serverIP takeagain.info -p 53 &
dig @$serverIP www.click-to-download.com -p 53 &
dig @$serverIP vastcoins.ru -p 53 &
dig @$serverIP www.sohbetsensin.com -p 53 &
dig @$serverIP bpmedspills.com -p 53 &
dig @$serverIP pantoneinkjet.com -p 53 &
dig @$serverIP www.anwar-rif.com -p 53 &
dig @$serverIP sbbbbteccojp.122.2o7.net -p 53 &
dig @$serverIP southwest.com.102.112.2o7.net -p 53 &
dig @$serverIP cpc3-stkn8-0-0-cust339.midd.cable.ntl.com -p 53 &
dig @$serverIP 616959.ds.nac.net -p 53 &
dig @$serverIP c951aeb7.virtua.com.br -p 53 &
dig @$serverIP isaoppa.info -p 53 &
dig @$serverIP porno-maxi-gratuit.com -p 53 &
dig @$serverIP adcount.ohmynews.com -p 53 &
dig @$serverIP mg5b.info -p 53 &
dig @$serverIP c-98-211-34-5.hsd1.tn.comcast.net -p 53 &
dig @$serverIP cpe-66-74-62-96.dc.res.rr.com -p 53 &
dig @$serverIP musicmembersarea.com -p 53 &
dig @$serverIP host71-67-dynamic.52-82-r.retail.telecomitalia.it -p 53 &
dig @$serverIP wc1133.91mt.com -p 53 &
dig @$serverIP forexkrobe.co.cc -p 53 &
dig @$serverIP tibiafreeitems.galeon.com -p 53 &
dig @$serverIP s4.reserver.ru -p 53 &
dig @$serverIP www.googleadcence.com -p 53 &
dig @$serverIP adultpasswordhacks.com -p 53 &
dig @$serverIP gkcek.chepushilasecurity8.com -p 53 &
dig @$serverIP swims.21tw.net -p 53 &
dig @$serverIP 1.aremosgooo.co.cc -p 53 &
dig @$serverIP cartoesnovos.250x.com -p 53 &
dig @$serverIP www.hobbystar.biz -p 53 &
dig @$serverIP cpc1-cdif1-0-0-cust973.cdif.cable.ntl.com -p 53 &
dig @$serverIP winfixer2006.com -p 53 &
dig @$serverIP www.24consultant-news.net -p 53 &
dig @$serverIP fullpcvirusscan.com -p 53 &
dig @$serverIP aolwpmqban.122.2o7.net -p 53 &
dig @$serverIP brokentwo.com -p 53 &
dig @$serverIP 14-176-82-209.g-net.net -p 53 &
dig @$serverIP worldgamemagazine.com -p 53 &
dig @$serverIP c-67-166-163-217.hsd1.va.comcast.net -p 53 &
dig @$serverIP fordaleltd.com -p 53 &
dig @$serverIP sertuddh33jf.com -p 53 &
dig @$serverIP ssdc.icelandair.is -p 53 &
dig @$serverIP shop.knight50heli.com -p 53 &
dig @$serverIP 4w8loss.com -p 53 &
dig @$serverIP celebwood.com -p 53 &
dig @$serverIP www.antivirus-2008-pro.org -p 53 &
dig @$serverIP alpek.net -p 53 &
dig @$serverIP adobe-security-server-us1.cz.cc -p 53 &
dig @$serverIP ad213.hpg.com.br -p 53 &
dig @$serverIP jscompressing.com -p 53 &
dig @$serverIP webdocs.ireit.com -p 53 &
dig @$serverIP romain-trystram.com -p 53 &
dig @$serverIP 79-79-149-119.dynamic.dsl.as9105.com -p 53 &
dig @$serverIP linhaky.cn -p 53 &
dig @$serverIP mail.american.hu -p 53 &
dig @$serverIP 1stbing.info -p 53 &
dig @$serverIP nuaswyn.cz.cc -p 53 &
dig @$serverIP www.glimpsebook.com -p 53 &
dig @$serverIP 152-176-28.dial.terra.cl -p 53 &
dig @$serverIP 1.amiral-system.mobi -p 53 &
dig @$serverIP phototype.cz.cc -p 53 &
dig @$serverIP reloadedproxy.info -p 53 &
dig @$serverIP computers.iwon.com -p 53 &
dig @$serverIP adsl-70-237-22-195.dsl.bcvloh.sbcglobal.net -p 53 &
dig @$serverIP evolvingsysinc.net -p 53 &
dig @$serverIP hosting2.pop.com.br -p 53 &
dig @$serverIP online-canadian-pharmacy.org -p 53 &
dig @$serverIP akril.info -p 53 &
dig @$serverIP super-hardcore-sex.com -p 53 &
dig @$serverIP sistema-z.ru -p 53 &
dig @$serverIP luckyshine.info -p 53 &
dig @$serverIP apelsinxxx.org -p 53 &
dig @$serverIP ad138.hpg.com.br -p 53 &
dig @$serverIP b.agilobable.pl -p 53 &
dig @$serverIP ct20865.ourtoolbar.com -p 53 &
dig @$serverIP monoartglass.com -p 53 &
dig @$serverIP 75-121-143-243.dyn.centurytel.net -p 53 &
dig @$serverIP fl-65-41-31-51.sta.embarqhsd.net -p 53 &
dig @$serverIP chiomega-ou.com -p 53 &
dig @$serverIP olwmteenhelponline.122.2o7.net -p 53 &
dig @$serverIP klickvip.com -p 53 &
dig @$serverIP itlist.com -p 53 &
dig @$serverIP ombligo.info -p 53 &
dig @$serverIP fatih55oguz.fa.funpic.de -p 53 &
dig @$serverIP gauntletvideos.powered-by.zango.com -p 53 &
dig @$serverIP www.livecams.nl -p 53 &
dig @$serverIP www.drugs-search.info -p 53 &
dig @$serverIP 215.red-83-42-56.dynamicip.rima-tde.net -p 53 &
dig @$serverIP down.koowo.com -p 53 &
dig @$serverIP acnq200.neoplus.adsl.tpnet.pl -p 53 &
dig @$serverIP creeksidemtncabins.com -p 53 &
dig @$serverIP perfig.com -p 53 &
dig @$serverIP sawt-gharb.com -p 53 &
dig @$serverIP s3.amazonaws.com -p 53 &
dig @$serverIP resusa.co.cr -p 53 &
dig @$serverIP tpgpost.122.2o7.net -p 53 &
dig @$serverIP www.repbblica.it -p 53 &
dig @$serverIP fancystarlight.com -p 53 &
dig @$serverIP mgwashingtonconews.112.2o7.net -p 53 &
dig @$serverIP www.trustgauge.com -p 53 &
dig @$serverIP adlx171.neoplus.adsl.tpnet.pl -p 53 &
dig @$serverIP ecruway.info -p 53 &
dig @$serverIP surfsix.info -p 53 &
dig @$serverIP hotmp3-download.com -p 53 &
dig @$serverIP img.ruclicks.com -p 53 &
dig @$serverIP googleupdate-01.com -p 53 &
dig @$serverIP 3apa3a.tomsk.tw -p 53 &
dig @$serverIP ol6.org -p 53 &
dig @$serverIP euskoweb.com -p 53 &
dig @$serverIP logyrush.info -p 53 &
dig @$serverIP extrapornmovies.com -p 53 &
dig @$serverIP st-agnes.de -p 53 &
dig @$serverIP turbina.cz.cc -p 53 &
dig @$serverIP misif.org.my -p 53 &
dig @$serverIP a85-138-121-27.cpe.netcabo.pt -p 53 &
dig @$serverIP iptool.info -p 53 &
dig @$serverIP banners.clips4sale.com -p 53 &
dig @$serverIP cruelstories.com -p 53 &
dig @$serverIP tysiaudpmt.pillsni.ru -p 53 &
dig @$serverIP e-warez.com -p 53 &
dig @$serverIP moonsappliances.com -p 53 &
dig @$serverIP www.pornvideohome.info -p 53 &
dig @$serverIP sendingproxy.tk -p 53 &
dig @$serverIP igld-84-229-13-157.inter.net.il -p 53 &
dig @$serverIP ww4.viewpornstars.com -p 53 &
dig @$serverIP r190-135-38-90.dialup.adsl.anteldata.net.uy -p 53 &
dig @$serverIP avast.d0wnloadz.net -p 53 &
dig @$serverIP www.cannabisbeer.com -p 53 &
dig @$serverIP liiff.ru -p 53 &
dig @$serverIP ehg-campmor.hitbox.com -p 53 &
dig @$serverIP www.mexicoteen.com -p 53 &
dig @$serverIP us.battle.net.zh-wck.in -p 53 &
dig @$serverIP 200.84.23-237.dyn.dsl.cantv.net -p 53 &
dig @$serverIP picture-convert.com -p 53 &
dig @$serverIP vtv3q.cn -p 53 &
dig @$serverIP partner1.kanoodle.com -p 53 &
dig @$serverIP zacho.medicw6.ru -p 53 &
dig @$serverIP unblocksoft.cz.cc -p 53 &
dig @$serverIP user.3721.com -p 53 &
dig @$serverIP www.hthez18.co.cc -p 53 &
dig @$serverIP unblock.org.uk -p 53 &
dig @$serverIP yellowcloak.info -p 53 &
dig @$serverIP ppp-74-8.20-151.libero.it -p 53 &
dig @$serverIP advert232.hpg.ig.com.br -p 53 &
dig @$serverIP tunestalk.com -p 53 &
dig @$serverIP prodownloadmanager.com -p 53 &
dig @$serverIP namooactors.com -p 53 &
dig @$serverIP unlimit-file-share.co.cc -p 53 &
dig @$serverIP webcelerator.com -p 53 &
dig @$serverIP 200-206-219-195.dsl.telesp.net.br -p 53 &
dig @$serverIP idollar.info -p 53 &
dig @$serverIP hitchcaddy.brinkster.net -p 53 &
dig @$serverIP ppp92-100-40-121.pppoe.avangarddsl.ru -p 53 &
dig @$serverIP motayam.net -p 53 &
dig @$serverIP zmbeunq.pillsni.ru -p 53 &
dig @$serverIP comcmdrun.com -p 53 &
dig @$serverIP www.iceak.net -p 53 &
dig @$serverIP zix.cz.cc -p 53 &
dig @$serverIP firefoxsurf.info -p 53 &
dig @$serverIP newsoftnewsworld.com -p 53 &
dig @$serverIP weldoo.com -p 53 &
dig @$serverIP dslb-092-076-150-227.pools.arcor-ip.net -p 53 &
dig @$serverIP crackz.ws -p 53 &
dig @$serverIP fulldownloadcrack.info -p 53 &
dig @$serverIP www.beyt.fvrshi.co.uk -p 53 &
dig @$serverIP 200-127-97-241.cab.prima.net.ar -p 53 &
dig @$serverIP 87-205-174-225.adsl.inetia.pl -p 53 &
dig @$serverIP envoidefichier.com -p 53 &
dig @$serverIP shareware.fixieonline.com -p 53 &
dig @$serverIP yourblenderparts.ru -p 53 &
dig @$serverIP down1.hahadownload.com -p 53 &
dig @$serverIP www.gifs-vorlagen.de -p 53 &
dig @$serverIP tj.114anhui.com -p 53 &
dig @$serverIP anis.ro -p 53 &
dig @$serverIP myspace-foto.net -p 53 &
dig @$serverIP videos-movie.com -p 53 &
dig @$serverIP brutapukamuk.com -p 53 &
dig @$serverIP ad.iconadserver.com -p 53 &
dig @$serverIP web-jogos.smtp.ru -p 53 &
dig @$serverIP www.wizcode.com -p 53 &
dig @$serverIP habbomynt.zzl.org -p 53 &
dig @$serverIP teletri.be -p 53 &
dig @$serverIP 14.osmot.in -p 53 &
dig @$serverIP dropweightonline.ru -p 53 &
dig @$serverIP free-link.co.kr -p 53 &
dig @$serverIP pornozver.com -p 53 &
dig @$serverIP bulerkoseddgasko.com -p 53 &
dig @$serverIP ashford.com.102.112.2o7.net -p 53 &
dig @$serverIP oyhn.com -p 53 &
dig @$serverIP ct66179.ourtoolbar.com -p 53 &
dig @$serverIP adult-forum.info -p 53 &
dig @$serverIP c-76-101-65-160.hsd1.fl.comcast.net -p 53 &
dig @$serverIP i121-113-35-50.s05.a020.ap.plala.or.jp -p 53 &
dig @$serverIP adek155.neoplus.adsl.tpnet.pl -p 53 &
dig @$serverIP reward.gaz.co.kr -p 53 &
dig @$serverIP www.albiondrugs.com -p 53 &
dig @$serverIP introstep.biz -p 53 &
dig @$serverIP hidealink.com -p 53 &
dig @$serverIP traforet.ru -p 53 &
dig @$serverIP bigpremiumlite.cn:8080 -p 53 &
dig @$serverIP dial-96.r5.gabrlt.infoave.net -p 53 &
dig @$serverIP hebus.love.easyrencontre.com -p 53 &
dig @$serverIP www.teslaplus.com -p 53 &
dig @$serverIP w.ultrawsurf.us -p 53 &
dig @$serverIP 87-205-39-30.adsl.inetia.pl -p 53 &
dig @$serverIP websnork.com -p 53 &
dig @$serverIP clickyahoo.info -p 53 &
dig @$serverIP e-motional.com -p 53 &
dig @$serverIP therapidbay.com -p 53 &
dig @$serverIP login543644.home.ro -p 53 &
dig @$serverIP luxbjsopticalcom.122.2o7.net -p 53 &
dig @$serverIP jinternetoptimizer.cjt1.net -p 53 &
dig @$serverIP fs11n2.sendspace.com -p 53 &
dig @$serverIP www.kicksbomb.com -p 53 &
dig @$serverIP 67.23.252.216 -p 53 &
dig @$serverIP r3load3d.oltreirc.net -p 53 &
dig @$serverIP leetfile.com -p 53 &
dig @$serverIP hopfast.info -p 53 &
dig @$serverIP tovail.be -p 53 &
dig @$serverIP cb.icq.com -p 53 &
dig @$serverIP lyqthbwl.cz.cc -p 53 &
dig @$serverIP eresmas.com -p 53 &
dig @$serverIP cee238.neoplus.adsl.tpnet.pl -p 53 &
dig @$serverIP ultimdefender.com -p 53 &
dig @$serverIP logon.povis.co.uk -p 53 &
dig @$serverIP forex-7.co.cc -p 53 &
dig @$serverIP qivmhbpwf.pillsni.ru -p 53 &
dig @$serverIP fastfb.tk -p 53 &
dig @$serverIP magictraffic.co.cc -p 53 &
dig @$serverIP awabo.com -p 53 &
dig @$serverIP scan-eranti-vnoew.com -p 53 &
dig @$serverIP mybigblackcock.org -p 53 &
dig @$serverIP zoombalo.com -p 53 &
dig @$serverIP schoolchoose.co.cc -p 53 &
dig @$serverIP habboretromaker.moonfruit.com -p 53 &
dig @$serverIP temple.ibi.pfizer.pillsgn.ru -p 53 &
dig @$serverIP relwqin.com -p 53 &
dig @$serverIP ashtartours.com -p 53 &
dig @$serverIP domainrein.com -p 53 &
dig @$serverIP tysia.sapte.ro -p 53 &
dig @$serverIP activesecurityshield.com -p 53 &
dig @$serverIP doorfile.in -p 53 &
dig @$serverIP unlimitedschool.com -p 53 &
dig @$serverIP adserver.wenters.com -p 53 &
dig @$serverIP techcareweb.in -p 53 &
dig @$serverIP antivirusscanopor.com -p 53 &
dig @$serverIP agems.com -p 53 &
dig @$serverIP v00d00.org -p 53 &
dig @$serverIP 58.83-213-248.dynamic.clientes.euskaltel.es -p 53 &
dig @$serverIP chiadodesign.pt -p 53 &
dig @$serverIP stafsoft.com -p 53 &
dig @$serverIP shushicom.nationprotect.net -p 53 &
dig @$serverIP brt-dsl-pool-228.dsl.bright.net -p 53 &
dig @$serverIP piscinasbcn.com -p 53 &
dig @$serverIP 53554d7a.cable.casema.nl -p 53 &
dig @$serverIP unblock-website.net -p 53 &
dig @$serverIP proxyhide.com -p 53 &
dig @$serverIP dpolada.cx.cc -p 53 &
dig @$serverIP pornwarez.com -p 53 &
dig @$serverIP www.c43858.com -p 53 &
dig @$serverIP formula-simracing.net -p 53 &
dig @$serverIP www.htid.co.uk -p 53 &
dig @$serverIP dgwwwdgmarketro.112.2o7.net -p 53 &
dig @$serverIP 81-149-133-95.pool.ukrtel.net -p 53 &
dig @$serverIP ozin.co.kr -p 53 &
dig @$serverIP myoutdoortv.com -p 53 &
dig @$serverIP robingood.beeglover.cn -p 53 &
dig @$serverIP mgwkrg.112.2o7.net -p 53 &
dig @$serverIP saxopeninsuladailynews.122.2o7.net -p 53 &
dig @$serverIP 214.sub-75-195-212.myvzw.com -p 53 &
dig @$serverIP www.cfugboston.org -p 53 &
dig @$serverIP actdataonline.in -p 53 &
dig @$serverIP esportvdfs.hpg.com.br -p 53 &
dig @$serverIP konishi-ballet.com -p 53 &
dig @$serverIP begawe.info -p 53 &
dig @$serverIP ynoubfa.cn -p 53 &
dig @$serverIP c-71-198-12-66.hsd1.ca.comcast.net -p 53 &
dig @$serverIP www.career-hound.com -p 53 &
dig @$serverIP codescannerprotectionwin.com -p 53 &
dig @$serverIP eniac2000.com -p 53 &
dig @$serverIP www.orelhas.pt -p 53 &
dig @$serverIP 201-27-172-12.dsl.telesp.net.br -p 53 &
dig @$serverIP pclnbdtn.co.tv -p 53 &
dig @$serverIP bypassit.be -p 53 &
dig @$serverIP www.sureseeker.com -p 53 &
dig @$serverIP caribouproxy.info -p 53 &
dig @$serverIP c83-248-209-57.bredband.comhem.se -p 53 &
dig @$serverIP ciorapi.home.ro -p 53 &
dig @$serverIP 1.berkem.in -p 53 &
dig @$serverIP 92.red-88-11-201.dynamicip.rima-tde.net -p 53 &
dig @$serverIP www.natwstb.com -p 53 &
dig @$serverIP united-ddl.com -p 53 &
dig @$serverIP tgobtcclsrgdlh.pillsni.ru -p 53 &
dig @$serverIP www.battle.net.en-us-adminwow-wordofwarcraft.com -p 53 &
dig @$serverIP deansplanet.com.powered-by.zango.com -p 53 &
dig @$serverIP gfacebook.info -p 53 &
dig @$serverIP theanimaltrust.com -p 53 &
dig @$serverIP geroika.net -p 53 &
dig @$serverIP ppp-124-121-180-253.revip2.asianet.co.th -p 53 &
dig @$serverIP dslb-088-070-043-164.pools.arcor-ip.net -p 53 &
dig @$serverIP gitradde.com -p 53 &
dig @$serverIP c-98-249-171-248.hsd1.fl.comcast.net -p 53 &
dig @$serverIP www.gsearch.co.kr -p 53 &
dig @$serverIP dirtybody.ru:8080 -p 53 &
dig @$serverIP m90-130-205-117.cust.tele2.se -p 53 &
dig @$serverIP songtoday.com -p 53 &
dig @$serverIP webmaster01.com.br -p 53 &
dig @$serverIP 201-68-174-73.dsl.telesp.net.br -p 53 &
dig @$serverIP bupv19.needstub.com -p 53 &
dig @$serverIP easykeylogger.com -p 53 &
dig @$serverIP www.temporo.it -p 53 &
dig @$serverIP www.vfwnnjtygeooiol.biz -p 53 &
dig @$serverIP www.imperialhavanese.com -p 53 &
dig @$serverIP tei.fivemillionfriends.com -p 53 &
dig @$serverIP lovetiles.com -p 53 &
dig @$serverIP goturssaved.rr.nu -p 53 &
dig @$serverIP xene.info -p 53 &
dig @$serverIP proxydefender.com -p 53 &
dig @$serverIP myw1doma.net.ph -p 53 &
dig @$serverIP www.hootershack.com -p 53 &
dig @$serverIP 95-52-23-101.dynamic.murmansk.dslavangard.ru -p 53 &
dig @$serverIP acyt55.neoplus.adsl.tpnet.pl -p 53 &
dig @$serverIP logc22.xiti.com -p 53 &
dig @$serverIP 2qnews.07x.net -p 53 &
dig @$serverIP raeality.sk -p 53 &
dig @$serverIP datingspace.net -p 53 &
dig @$serverIP xqoyjkmnrhqmxpty.net -p 53 &
dig @$serverIP palsys.ca -p 53 &
dig @$serverIP u8.plus-on.co.kr -p 53 &
dig @$serverIP hmcompany.info -p 53 &
dig @$serverIP host31-206-dynamic.20-79-r.retail.telecomitalia.it -p 53 &
dig @$serverIP fast-transfer.co.cc -p 53 &
dig @$serverIP ppp-186-9.20-151.libero.it -p 53 &
dig @$serverIP rarita.ru -p 53 &
dig @$serverIP avsscanspeedwin.com -p 53 &
dig @$serverIP testdomainforapi.com -p 53 &
dig @$serverIP no4.dothost.co.kr -p 53 &
dig @$serverIP epb133.neoplus.adsl.tpnet.pl -p 53 &
dig @$serverIP y.sopani.pfizer.pillscy.ru -p 53 &
dig @$serverIP pfizer.viagra.yvo.kapills.ru -p 53 &
dig @$serverIP remont-rab.ru -p 53 &
dig @$serverIP epriego.mytowntoolbar.com -p 53 &
dig @$serverIP pool-68-239-181-202.nwrk.east.verizon.net -p 53 &
dig @$serverIP privacyanywhere.com -p 53 &
dig @$serverIP torrentq.com -p 53 &
dig @$serverIP radio-rendevous.de -p 53 &
dig @$serverIP macaroni.in -p 53 &
dig @$serverIP janitasaels.blogspot.com -p 53 &
dig @$serverIP americanliit.cn -p 53 &
dig @$serverIP host-87-101-16-43.proxnet.pl -p 53 &
dig @$serverIP accessthenet.info -p 53 &
dig @$serverIP vvps.ws -p 53 &
dig @$serverIP wareztoday.blogspot.com -p 53 &
dig @$serverIP sidxxxvids55.tk -p 53 &
dig @$serverIP ppp91-122-163-24.pppoe.avangarddsl.ru -p 53 &
dig @$serverIP dnold.tabbrowser.co.kr -p 53 &
dig @$serverIP adsl-76-232-54-156.dsl.lsan03.sbcglobal.net -p 53 &
dig @$serverIP www.matudesign.com -p 53 &
dig @$serverIP dgglobal.112.2o7.net -p 53 &
dig @$serverIP xunlei6x.com -p 53 &
dig @$serverIP malabo.thruhere.net:8080 -p 53 &
dig @$serverIP exficale.com -p 53 &
dig @$serverIP ppp-124-121-34-110.revip2.asianet.co.th -p 53 &
dig @$serverIP nettbook.org -p 53 &
dig @$serverIP avyewi.cn -p 53 &
dig @$serverIP f5.cookingluck.com -p 53 &
dig @$serverIP awesomeproxy.info -p 53 &
dig @$serverIP ajiaaawamlc.com -p 53 &
dig @$serverIP traffic-in.com -p 53 &
dig @$serverIP alimama.com -p 53 &
dig @$serverIP going-to-n.com -p 53 &
dig @$serverIP naturalproxy.com -p 53 &
dig @$serverIP longhairedsingles.com -p 53 &
dig @$serverIP papaforex.co.cc -p 53 &
dig @$serverIP antivirusmart.com -p 53 &
dig @$serverIP by.googlestat50.in -p 53 &
dig @$serverIP adtm57.neoplus.adsl.tpnet.pl -p 53 &
dig @$serverIP www.carldesrosiers.com -p 53 &
dig @$serverIP fivewjet.com -p 53 &
dig @$serverIP njvj.t35.com -p 53 &
dig @$serverIP markandrews.net -p 53 &
dig @$serverIP ibjtk.loyaltytoolbar.com -p 53 &
dig @$serverIP qlhloosfitoslvdq.biz -p 53 &
dig @$serverIP simplified.clawed.info -p 53 &
dig @$serverIP pihbinmhgpwjkpt.biz -p 53 &
dig @$serverIP www.hackingedge.com -p 53 &
dig @$serverIP rxnic.com -p 53 &
dig @$serverIP kaael.in -p 53 &
dig @$serverIP c-67-187-160-128.hsd1.ca.comcast.net -p 53 &
dig @$serverIP www.devilx64wox64.co.cc -p 53 &
dig @$serverIP www.rirefun.com -p 53 &
dig @$serverIP www.albierospesa.it -p 53 &
dig @$serverIP forumdason.myforumtoolbar.com -p 53 &
dig @$serverIP smart-scanforu.uni.cc -p 53 &
dig @$serverIP download.onlinewelten.com -p 53 &
dig @$serverIP web.axelero.hu -p 53 &
dig @$serverIP 181-196-187-203.static.youtele.com -p 53 &
dig @$serverIP quicksweeper.com -p 53 &
dig @$serverIP blainblainprinciotta.blogspot.com -p 53 &
dig @$serverIP u5687.48.spylog.com -p 53 &
dig @$serverIP 1gig-antivirus.com -p 53 &
dig @$serverIP www.acb.bs.it -p 53 &
dig @$serverIP ppctracking.net -p 53 &
dig @$serverIP habboloco.net -p 53 &
dig @$serverIP coraldavaiderm.com -p 53 &
dig @$serverIP www.interiordesigner.in -p 53 &
dig @$serverIP habboserver.atspace.com -p 53 &
dig @$serverIP crack.pagina.nl -p 53 &
dig @$serverIP liveenterprisesuite.com -p 53 &
dig @$serverIP yandekapi.com -p 53 &
dig @$serverIP download5.spyaxe.com -p 53 &
dig @$serverIP 190-39-13-132.dyn.dsl.cantv.net -p 53 &
dig @$serverIP www.solodiyi.com -p 53 &
dig @$serverIP www.leastguide.com -p 53 &
dig @$serverIP 123tagged.com -p 53 &
dig @$serverIP www4lilli.co.cc -p 53 &
dig @$serverIP www.cracksex.com -p 53 &
dig @$serverIP windows-helpcenter.com -p 53 &
dig @$serverIP www.registrycleanerpro.org -p 53 &
dig @$serverIP lsjmp.com -p 53 &
dig @$serverIP www.kokporn.info -p 53 &
dig @$serverIP juicyqueef.com -p 53 &
dig @$serverIP c-71-193-239-186.hsd1.or.comcast.net -p 53 &
dig @$serverIP traffixinc.com -p 53 &
dig @$serverIP www.cardfountain.com -p 53 &
dig @$serverIP hqxvideofree.com -p 53 &
dig @$serverIP start-search.com -p 53 &
dig @$serverIP zoomthat.info -p 53 &
dig @$serverIP oofun.com -p 53 &
dig @$serverIP linfoxdomain.com -p 53 &
dig @$serverIP clickmedq.fileave.com -p 53 &
dig @$serverIP 95-28-112-109.broadband.corbina.ru -p 53 &
dig @$serverIP sslproxy.mobi -p 53 &
dig @$serverIP i-am-porno-star.net -p 53 &
dig @$serverIP charlizetheron.sexybabesx.com -p 53 &
dig @$serverIP young-service.com -p 53 &
dig @$serverIP a85-138-151-128.cpe.netcabo.pt -p 53 &
dig @$serverIP netmovie-tube-aias.co.cc -p 53 &
dig @$serverIP zmp3.net -p 53 &
dig @$serverIP poolmwq.in -p 53 &
dig @$serverIP pc9-218.chomiczowka.waw.pl -p 53 &
dig @$serverIP psn.cn -p 53 &
dig @$serverIP prisacom.112.2o7.net -p 53 &
dig @$serverIP cannabisfx.com -p 53 &
dig @$serverIP zonadialer.com -p 53 &
dig @$serverIP herbalifes.servehalflife.com -p 53 &
dig @$serverIP fwkrqzsfjmrrr.com -p 53 &
dig @$serverIP browserstat.in -p 53 &
dig @$serverIP durposty.com -p 53 &
dig @$serverIP slp8.co.cc -p 53 &
dig @$serverIP s.xvideos.com -p 53 &
dig @$serverIP paypal-area-verify-account.synergia.com.mx -p 53 &
dig @$serverIP adserver1.backbeatmedia.com -p 53 &
dig @$serverIP mugyra.org -p 53 &
dig @$serverIP nevehaqyxixocu.com -p 53 &
dig @$serverIP delivery001.com -p 53 &
dig @$serverIP rascunho.qipim.ru -p 53 &
dig @$serverIP equipeworldsound.com.br -p 53 &
dig @$serverIP puskovayaustanovka.ru -p 53 &
dig @$serverIP cpe-69-206-246-61.hvc.res.rr.com -p 53 &
dig @$serverIP scbm.com -p 53 &
dig @$serverIP 192.sub-70-220-201.myvzw.com -p 53 &
dig @$serverIP cpe-76-169-103-142.socal.res.rr.com -p 53 &
dig @$serverIP yalupa.com -p 53 &
dig @$serverIP domain454002.com -p 53 &
dig @$serverIP napiwis54353.com -p 53 &
dig @$serverIP adsl-75-34-33-53.dsl.chcgil.sbcglobal.net -p 53 &
dig @$serverIP www.spekband.com -p 53 &
dig @$serverIP mattressusa.122.2o7.net -p 53 &
dig @$serverIP stats.wordpress.com -p 53 &
dig @$serverIP cont.muiet.com -p 53 &
dig @$serverIP filmcodec.net -p 53 &
dig @$serverIP new.egycontra.com -p 53 &
dig @$serverIP orginalcrack.net -p 53 &
dig @$serverIP cod4hacks.org -p 53 &
dig @$serverIP secureroom.co.cc -p 53 &
dig @$serverIP bsn-61-115-97.dial-up.dsl.siol.net -p 53 &
dig @$serverIP 9rk1.co.cc -p 53 &
dig @$serverIP w7-guardav.biz -p 53 &
dig @$serverIP curiousmedia.com.au -p 53 &
dig @$serverIP multy-protect.co.cc -p 53 &
dig @$serverIP edd51.neoplus.adsl.tpnet.pl -p 53 &
dig @$serverIP www.timelyweb.com -p 53 &
dig @$serverIP www.jointventureforprofit.com -p 53 &
dig @$serverIP upccodes.co.uk -p 53 &
dig @$serverIP ewa111.neoplus.adsl.tpnet.pl -p 53 &
dig @$serverIP dragger.info -p 53 &
dig @$serverIP reich.inairen.pfizer.rapills.ru -p 53 &
dig @$serverIP justificatory.net -p 53 &
dig @$serverIP c-71-226-194-120.hsd1.nj.comcast.net -p 53 &
dig @$serverIP soft.telecharger.com -p 53 &
dig @$serverIP adsl-69-151-132-101.dsl.hstntx.swbell.net -p 53 &
dig @$serverIP transaction-idcdt.com -p 53 &
dig @$serverIP ynprurio.pillsni.ru -p 53 &
dig @$serverIP filesharingfriends.com -p 53 &
dig @$serverIP zebland.free.fr -p 53 &
dig @$serverIP ad248.hpg.ig.com.br -p 53 &
dig @$serverIP wevecohesikyv.com -p 53 &
dig @$serverIP medicfg4.ru -p 53 &
dig @$serverIP expressdelivery.biz -p 53 &
dig @$serverIP downloads.pixesplacen10.com -p 53 &
dig @$serverIP dsjkg34.cz.cc -p 53 &
dig @$serverIP mylifedownloads.info -p 53 &
dig @$serverIP storage.filetolink.com -p 53 &
dig @$serverIP config.spyspotter.com -p 53 &
dig @$serverIP woxijaquhiqal.com -p 53 &
dig @$serverIP 92-249-240-128.pool.digikabel.hu -p 53 &
dig @$serverIP www.folusho.com -p 53 &
dig @$serverIP techunblock.info -p 53 &
dig @$serverIP whiskeymilitia.com.102.112.2o7.net -p 53 &
dig @$serverIP gg-work.com -p 53 &
dig @$serverIP myxmad.com -p 53 &
dig @$serverIP suereva.it -p 53 &
dig @$serverIP free.888.com -p 53 &
dig @$serverIP attorney2u.info -p 53 &
dig @$serverIP naps1337.na.ohost.de -p 53 &
dig @$serverIP boas1673.freevar.com -p 53 &
dig @$serverIP ejacattack.free.fr -p 53 &
dig @$serverIP kdre.info -p 53 &
dig @$serverIP avsxpridewinonline.com -p 53 &
dig @$serverIP www.lajnux.nu -p 53 &
dig @$serverIP www.serialsuceuse.com -p 53 &
dig @$serverIP www.new-folder-virus.com -p 53 &
dig @$serverIP 3ara3a.com -p 53 &
dig @$serverIP hurrypast.info -p 53 &
dig @$serverIP hdxxxvideoonline.com -p 53 &
dig @$serverIP av-protect.com -p 53 &
dig @$serverIP sticksurf.info -p 53 &
dig @$serverIP adobecodec-02.co.tv -p 53 &
dig @$serverIP gpaper232.112.2o7.net -p 53 &
dig @$serverIP argotsuva.monbe.be -p 53 &
dig @$serverIP costfuel.com -p 53 &
dig @$serverIP timezero.freehostia.com -p 53 &
dig @$serverIP weight-software.in -p 53 &
dig @$serverIP sledmerehouse.info -p 53 &
dig @$serverIP p4fc94b78.dip.t-dialin.net -p 53 &
dig @$serverIP 84-72-141-172.dclient.hispeed.ch -p 53 &
dig @$serverIP rwmrs.medicw9.ru -p 53 &
dig @$serverIP commovie-t5l9.co.cc -p 53 &
dig @$serverIP theprotectionxpwin.com -p 53 &
dig @$serverIP ackerbell.com -p 53 &
dig @$serverIP firesharing.myuniversitytoolbar.com -p 53 &
dig @$serverIP www.2345.com -p 53 &
dig @$serverIP web-warez.info -p 53 &
dig @$serverIP xxunblockxx.info -p 53 &
dig @$serverIP ucdq.com -p 53 &
dig @$serverIP hotel-sas.ru -p 53 &
dig @$serverIP 84-73-124-151.dclient.hispeed.ch -p 53 &
dig @$serverIP cdn.openinstall.com.s3.amazonaws.com -p 53 &
dig @$serverIP easypccleaner.net -p 53 &
dig @$serverIP www.snooper.se -p 53 &
dig @$serverIP cpe-76-167-44-139.socal.res.rr.com -p 53 &
dig @$serverIP windows-mobile.crack.serial.keygen.ddlone.com -p 53 &
dig @$serverIP download-drivers.org -p 53 &
dig @$serverIP ytecelav.freewaywebhost.com -p 53 &
dig @$serverIP wsdefender-nbev.co.cc -p 53 &
dig @$serverIP aolwpicq.122.2o7.net -p 53 &
dig @$serverIP netsetter.net -p 53 &
dig @$serverIP margincallforex.co.cc -p 53 &
dig @$serverIP gcirm.delmarvanow.gcion.com -p 53 &
dig @$serverIP saselinux.com -p 53 &
dig @$serverIP eliteshells.net -p 53 &
dig @$serverIP wolfinsen.wo.funpic.org -p 53 &
dig @$serverIP iswhack.com -p 53 &
dig @$serverIP spywareremoval.bulletproofsoft.com -p 53 &
dig @$serverIP longtraffic.com -p 53 &
dig @$serverIP d34ghqarfrgad.com -p 53 &
dig @$serverIP sexypupsik.cn -p 53 &
dig @$serverIP homemadesandwiches.com -p 53 &
dig @$serverIP zjz-002.com -p 53 &
dig @$serverIP www.modul.yoyo.pl -p 53 &
dig @$serverIP accountinge2e4.info -p 53 &
dig @$serverIP clickmepp.fileave.com -p 53 &
dig @$serverIP 203-74.pptp.artx.ru -p 53 &
dig @$serverIP 4-181-152-216.mtaonline.net -p 53 &
dig @$serverIP transaction-idst.com -p 53 &
dig @$serverIP waystounblockmyspace.com -p 53 &
dig @$serverIP wfvnigzw.co.tv -p 53 &
dig @$serverIP nxrywtl.co.tv -p 53 &
dig @$serverIP www.limewire-download-pro.com -p 53 &
dig @$serverIP nuestros-sabores.com.ar -p 53 &
dig @$serverIP host181-219-dynamic.10-79-r.retail.telecomitalia.it -p 53 &
dig @$serverIP whatsyoursearch.com -p 53 &
dig @$serverIP www.capitalotb.com -p 53 &
dig @$serverIP amateurcleavage.com -p 53 &
dig @$serverIP 93-173-152-185.bb.netvision.net.il -p 53 &
dig @$serverIP dark.malpro.in -p 53 &
dig @$serverIP surfmafia.info -p 53 &
dig @$serverIP w.escom.bg -p 53 &
dig @$serverIP toolista.com -p 53 &
dig @$serverIP ad103.hpg.ig.com.br -p 53 &
dig @$serverIP dwn.bookupd.com -p 53 &
dig @$serverIP vbmet.com -p 53 &
dig @$serverIP indersex.info -p 53 &
dig @$serverIP gamezprumz.com -p 53 &
dig @$serverIP s7.blingblingcontent.com -p 53 &
dig @$serverIP c-67-162-50-194.hsd1.il.comcast.net -p 53 &
dig @$serverIP 183.69-54-92.telenet.ru -p 53 &
dig @$serverIP auhhorize.com -p 53 &
dig @$serverIP www.simpsonscity.com -p 53 &
dig @$serverIP j776loap2987m.com -p 53 &
dig @$serverIP download.joomlaportal.ch -p 53 &
dig @$serverIP bestantivirus1.com.xorg.pl -p 53 &
dig @$serverIP g68.rwd.prospect.pl -p 53 &
dig @$serverIP handanal.fileave.com -p 53 &
dig @$serverIP crapola.info -p 53 &
dig @$serverIP mgwsls.112.2o7.net -p 53 &
dig @$serverIP kehhk.mq34.net -p 53 &
dig @$serverIP baixararquivos.com.sapo.pt -p 53 &
dig @$serverIP 218-162-158-196.dynamic.hinet.net -p 53 &
dig @$serverIP ip-94.146.bulloch.net -p 53 &
dig @$serverIP www.amateurs.whackfactor.com -p 53 &
dig @$serverIP w14.hitbox.com -p 53 &
dig @$serverIP j180158.upc-j.chello.nl -p 53 &
dig @$serverIP surfclear.co.cc -p 53 &
dig @$serverIP google-com-vn.masrawy.com.google-com-pk.thetruehelp.ru:8080 -p 53 &
dig @$serverIP hiload.in -p 53 &
dig @$serverIP fsaconstructora.cl -p 53 &
dig @$serverIP mbers.ozemail.com.au -p 53 &
dig @$serverIP chasunee.shacknet.nu:8080 -p 53 &
dig @$serverIP naturalconnections.com -p 53 &
dig @$serverIP gamedase.ru -p 53 &
dig @$serverIP idkqzshcjxr.com -p 53 &
dig @$serverIP dslb-084-056-106-229.pools.arcor-ip.net -p 53 &
dig @$serverIP 95-37-236-23.dynamic.mts-nn.ru -p 53 &
dig @$serverIP suburbanrun.com -p 53 &
dig @$serverIP p2024-ipbf503kobeminato.hyogo.ocn.ne.jp -p 53 &
dig @$serverIP puttvtuosdrifumn.org -p 53 &
dig @$serverIP www.fulldlzone.com -p 53 &
dig @$serverIP current-download-online.com -p 53 &
dig @$serverIP ebatvsehbabnasvete.ru -p 53 &
dig @$serverIP down.smartboan.com -p 53 &
dig @$serverIP portioncenter.com -p 53 &
dig @$serverIP bitslinker.com -p 53 &
dig @$serverIP apex36.cn -p 53 &
dig @$serverIP ixejos.cn -p 53 &
dig @$serverIP temp.hilightsredsea.com -p 53 &
dig @$serverIP i114-180-51-111.s04.a013.ap.plala.or.jp -p 53 &
dig @$serverIP trffc3.ru -p 53 &
dig @$serverIP host126-219-dynamic.16-79-r.retail.telecomitalia.it -p 53 &
dig @$serverIP ypolois.cz.cc -p 53 &
dig @$serverIP birdiedanwg.tripod.com -p 53 &

done

