<!DOCTYPE html>
<html>
	<head>
		<title>You have been blocked</title>
		<link rel="stylesheet" type="text/css" href="/css/default.css" />
		<script language="javascript" src="/js/functions.js"></script>
	</head>
	<body onload="javascript:autoDisplay();">
		<div id="forIframe" style="display: none;">
			<a href="#" target="_blank"><img id="iframeLogo" src="/images/logo_blocked.png" alt="Blocked by AvauntGuard" /></a>
		</div>
		<div id="centered" style="display: none;">
			<table>
				<tr><td colspan="2"><h1>Blocked by ScreenDNS</h1></td></tr>
				<tr>
					<td>
						<img src="/images/logo.png" alt="AvauntGuard logo" />
					</td>
					<td>